GET http://localhost:3000/api/v1/users


### Create user

POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "username": "user1",
    "password": "password12"
}

### Login user
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password12"
}

###

GET http://localhost:3000/api/v1/catches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidXNlcjEiLCJpYXQiOjE2MTQ0NTUyMTYsImV4cCI6MTYxNDQ1ODgxNn0.XA93gyM_URhs85ITuZVgPKiYIGHCDy8QyR0kfXNa1d4

### Catch requests---------------

### Get all catches
GET http://localhost:3000/api/v1/catches

### Add new catch
POST http://localhost:3000/api/v1/catches
Content-Type: application/json

{
    "username": "user1",
    "fishType": "bass",
    "fishLength": "20cm",
    "fishWeight": "1000g",
    "longAndLatPos": "41.40338, 2.17403",
    "city": "Ankeborg",
    "lake": "plasket",
}
###

POST http://localhost:3000/api/v1/catches
Content-Type: application/json

{
    "username": "user1",
    "fishType": "bass",
    "fishLength": "20cm",
    "fishWeight": "1000g",
    "longAndLatPos": "41.40338, 2.17403",
    "city": "Ankeborg",
    "lake": "plasket"
}