GET http://localhost:3000/


### Create user

POST http://localhost:3000/user/
Content-Type: application/json

{
    "username": "user1",
    "password": "password2"
}

### Login user
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password2"
}

###

GET http://localhost:3000/user/logged-in
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjIiLCJpYXQiOjE2MTI4NjI0NDIsImV4cCI6MTYxMjg2NjA0Mn0.Ob9zNU4JBVs7E8d5aprJGc2PkVKlSmgTQY_SOILJaI8
