### Home
GET http://localhost:3000/api/v1/

### Get all users
GET http://localhost:3000/api/v1/users


### Create user

POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "username": "mattias",
    "password": "password12"
}

### Login user
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "username": "mattias",
    "password": "password12"
}

### Delete user
DELETE  http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "username": "user2"
}

###

GET http://localhost:3000/api/v1/catches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidXNlcjEiLCJpYXQiOjE2MTQ0NTUyMTYsImV4cCI6MTYxNDQ1ODgxNn0.XA93gyM_URhs85ITuZVgPKiYIGHCDy8QyR0kfXNa1d4

### Catch requests---------------

### Get all catches
GET http://localhost:3000/api/v1/catches

### Get one users catches
GET http://localhost:3000/api/v1/catches/user2

### Add new catch
POST http://localhost:3000/api/v1/catches/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoibWF0dGlhcyIsImlhdCI6MTYxNDYwODMwNSwiZXhwIjoxNjE0NjExOTA1fQ.3VIYXd-GufbYeDG467YbXYpBvXfvNiD3uD4RbhsRFjE
Content-Type: application/json

{
    "username": "mattias",
    "fishType": "perch",
    "fishLength": "25cm",
    "fishWeight": "800g",
    "longAndLatPos": "57.957988, 12.725058",
    "city": "Vårgårda",
    "lake": "StorSjön"
}

### Update catch

PUT http://localhost:3000/api/v1/catches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidXNlcjIiLCJpYXQiOjE2MTQ2MDU1NjEsImV4cCI6MTYxNDYwOTE2MX0.4Z3a5N8ePorVImMXEdlHR1XRpLrJCx2A_8E_xXJN5-M
Content-Type: application/json

{
    "id": "603cdcc24612585bb0cebc30", 
    "username": "user2",
    "fishType": "bass",
    "fishLength": "20cm",
    "fishWeight": "1000g",
    "longAndLatPos": "41.40338, 2.17403",
    "city": "Ankeborg",
    "lake": "plaskdammen"
}
### Update catch only length

PUT http://localhost:3000/api/v1/catches
Content-Type: application/json

{
    "id": "603b3f36d6335d39f442689e", 
    "username": "user1",
    "fishLength": "20cm"

}
### Delete catch

DELETE http://localhost:3000/api/v1/catches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoibWF0dGlhcyIsImlhdCI6MTYxNDYwODMwNSwiZXhwIjoxNjE0NjExOTA1fQ.3VIYXd-GufbYeDG467YbXYpBvXfvNiD3uD4RbhsRFjE
Content-Type: application/json

{
    "id": "603cf5db73475b35945c06f6", 
    "username": "user1"
}

### Webhooks ---------------------------------------

### Get all subscribers
GET http://localhost:3000/api/v1/webhook

### Create new subscriber

POST http://localhost:3000/api/v1/webhook
Content-Type: application/json

{
    "url": "http://localhost:5000/webhooks"
}
### Notify subscribers
POST http://localhost:3000/api/v1/webhook/notify-subscribers
Content-Type: application/json

{
    "message": "Meddelande fran webhook"
}
